test_0 (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for file creation: ./lab5a.py ... ok
test_a (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for errors running: ./lab5a.py ... ok
test_a1 (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for correct shebang line: ./lab5a.py ... ok
test_a1_author_id (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Correct Script ID - match system ID: ./lab5a.py ... skipped 'skipping userid check.'
test_a_function_read_file_string (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - function read_file_string fails without 1 argument ... ok
test_b_function_read_file_list (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - function read_file_list fails without 1 argument ... ok
test_c_file_data_txt_exists (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for file creation: ./data.txt ... ok
test_d_file_data_txt_has_correct_text (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for correct contents: ./data.txt ... ok
test_e_function_read_file_string_correct_output (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for output: ./lab5a.py ... ok
test_f_function_read_file_list_correct_output (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for output: ./lab5a.py ... ok
test_g_function_read_file_list_correct_output (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for output: ./lab5a.py ... ok
test_h_function_read_file_list_correct_output (__main__.lab5a)
[Lab 5] - [Investigation 1] - [Part 1] - Files - Test for output: ./lab5a.py ... ok
test_0 (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for file creation: ./lab5b.py ... ok
test_a (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for errors running: ./lab5b.py ... ok
test_a1 (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for correct shebang line: ./lab5b.py ... ok
test_a1_author_id (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Correct Script ID - match system ID: ./lab5b.py ... skipped 'skipping userid check.'
test_a_function_append_file_string (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - function append_file_string fails without 2 argument ... ok
test_a_function_read_file_string (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - function read_file_string fails without 1 argument ... ok
test_b_function_read_file_list (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - function read_file_list fails without 1 argument ... ok
test_c_function_write_file_list (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - function write_file_list fails without 2 argument ... ok
test_d_function_copy_file_add_line_numbers (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - function copy_file_add_line_numbers fails without 2 argument ... ok
test_e_file_data_txt_exists (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for file creation: ./data.txt ... ok
test_f_file_data_txt_has_correct_text (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for correct contents: ./data.txt ... ok
test_g_function_read_file_string_correct_output (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... /home/ahscott/ops445/lab5/./CheckLab5.py:235: ResourceWarning: unclosed file <_io.TextIOWrapper name='data.txt' mode='r' encoding='UTF-8'>
  self.assertEqual(lab5bStudent.read_file_string(filename), answer, msg=error_output)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_h_function_read_file_list_correct_output (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... ok
test_i_function_append_file_string_correct_output_1 (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... /home/ahscott/ops445/lab5/./CheckLab5.py:262: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca1.txt.checkscript' mode='r' encoding='UTF-8'>
  self.assertEqual(lab5bStudent.read_file_string(filename), answer, msg=error_output)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_i_function_append_file_string_correct_output_2 (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... /home/ahscott/ops445/lab5/./CheckLab5.py:278: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca1.txt.checkscript' mode='r' encoding='UTF-8'>
  self.assertEqual(lab5bStudent.read_file_string(filename), answer, msg=error_output)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_j_function_write_file_list_correct_output_1 (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... /home/ahscott/ops445/lab5/./CheckLab5.py:294: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca2.txt.checkscript' mode='r' encoding='UTF-8'>
  self.assertEqual(lab5bStudent.read_file_string(filename), answer, msg=error_output)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_j_function_write_file_list_correct_output_2 (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... /home/ahscott/ops445/lab5/./CheckLab5.py:310: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca2.txt.checkscript' mode='r' encoding='UTF-8'>
  self.assertEqual(lab5bStudent.read_file_string(filename), answer, msg=error_output)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_k_function_copy_file_add_line_numbers_correct_output_1 (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... /home/ahscott/ops445/lab5/./CheckLab5.py:325: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca3.txt.checkscript' mode='r' encoding='UTF-8'>
  self.assertEqual(lab5bStudent.read_file_string(tempfile), answer, msg=error_output)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_k_function_copy_file_add_line_numbers_correct_output_2 (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... /home/ahscott/ops445/lab5/./CheckLab5.py:341: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca3.txt.checkscript' mode='r' encoding='UTF-8'>
  self.assertEqual(lab5bStudent.read_file_string(tempfile), answer, msg=error_output)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_k_function_copy_file_add_line_numbers_correct_output_3 (__main__.lab5b)
[Lab 5] - [Investigation 1] - [Part 2] - Files - Test for output: ./lab5b.py ... /home/ahscott/ops445/lab5/./CheckLab5.py:354: ResourceWarning: unclosed file <_io.TextIOWrapper name='seneca4.txt.checkscript' mode='r' encoding='UTF-8'>
  self.assertEqual(lab5bStudent.read_file_string(tempfile), answer, msg=error_output)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_0 (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for file creation: ./lab5c.py ... ok
test_a (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for errors running: ./lab5c.py ... ok
test_a1 (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for correct shebang line: ./lab5c.py ... ok
test_a1_author_id (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Correct Script ID - match system ID: ./lab5c.py ... skipped 'skipping userid check.'
test_a_function_add (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - function add fails without 2 argument ... ok
test_b_function_read_file (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - function read_file fails without 1 argument ... ok
test_c_function_add_correct_output_1 (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for output: ./lab5c.py ... ok
test_c_function_add_correct_output_2 (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for output: ./lab5c.py ... ok
test_c_function_add_correct_output_3 (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for output: ./lab5c.py ... ok
test_c_function_add_correct_output_4 (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for output: ./lab5c.py ... ok
test_d_function_read_file_correct_output_1 (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for output: ./lab5c.py ... ok
test_d_function_read_file_correct_output_2 (__main__.lab5c)
[Lab 5] - [Investigation 2] - [Part 1] - Files - Test for output: ./lab5c.py ... ok

----------------------------------------------------------------------
Ran 44 tests in 0.084s

OK (skipped=3)
OPS435 Lab Report - System Information for running ./CheckLab5.py
=================================================================
    User login name: ahscott
    Linux system name: fedora
    Linux system version: Fedora release 34 (Thirty Four)
    Python executable: /usr/bin/python3
    Python version: 3910
    OS Platform: linux
    Working Directory: /home/ahscott/ops445/lab5
    Start at: Sat Feb 19 17:02:04 2022
=================================================================
